# Generated by Django 4.2.6 on 2023-11-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderApp', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
